[package]
name = "explorer"
version = "0.1.0"
authors = ["elaineo <elaine.ou@gmail.com>"]

[[bin]]
name = "explorer-rs"
path = "src/main.rs"

[dependencies]
leveldb = "*"
rustc-serialize = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
gethrpc = { path = './gethrpc' }
